In [6]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/yelp-dataset/Dataset_User_Agreement.pdf
/kaggle/input/yelp-dataset/yelp_academic_dataset_review.json
/kaggle/input/yelp-dataset/yelp_academic_dataset_checkin.json
/kaggle/input/yelp-dataset/yelp_academic_dataset_business.json
/kaggle/input/yelp-dataset/yelp_academic_dataset_tip.json
/kaggle/input/yelp-dataset/yelp_academic_dataset_user.json


In [7]:
import json

dataset_review = '/kaggle/input/yelp-dataset/yelp_academic_dataset_review.json'

data = []
with open(dataset_review, 'r') as file:
    for i, line in enumerate(file):
        if i >= 500000:  
            break
        data.append(json.loads(line))

# DataFrame'e dönüştür
df_review = pd.DataFrame(data)

# 5 satırı datasetinin
df_review.head()

review_id                 user_id             business_id  \
0  KU_O5udG6zpxOg-VcAEodg  mh_-eMZ6K5RLWhZyISBhwA  XQfwVwDr-v0ZS3_CbbE5Xw   
1  BiTunyQ73aT9WBnpR9DZGw  OyoGAe7OKpv6SyGZT5g77Q  7ATYjTIgM3jUlt4UM3IypQ   
2  saUsX_uimxRlCVr67Z4Jig  8g_iMtfSiwikVnbP2etR0A  YjUWPpI6HXG530lwP-fb2A   
3  AqPFMleE6RsU23_auESxiA  _7bHUi9Uuf5__HHc_Q8guQ  kxX2SOes4o-D3ZQBkiMRfA   
4  Sx8TMOWLNuJBWer-0pcmoA  bcjbaE6dDog4jkNY91ncLQ  e4Vwtrqf-wpJfwesgvdgxQ   

   stars  useful  funny  cool  \
0    3.0       0      0     0   
1    5.0       1      0     1   
2    3.0       0      0     0   
3    5.0       1      0     1   
4    4.0       1      0     1   

                                                text                 date  
0  If you decide to eat here, just be aware it is...  2018-07-07 22:09:11  
1  I've taken a lot of spin classes over the year...  2012-01-03 15:28:18  
2  Family diner. Had the buffet. Eclectic assortm...  2014-02-05 20:30:30  
3  Wow!  Yummy, different,  delicious.   Our favo...  2015-01-04 00:01:03  
4  Cute interior and owner (?) gave us tour of up...  2017-01-14 20:54:15

In [8]:
#Diğer kod satırında yapılan sürecin hızlandırılmış veri temizleme süreci
business_review_counts = df_review["business_id"].value_counts()
business_mostreviews = [business_review_counts.index[i] for i in range(5)]
dataset_business = pd.read_json("/kaggle/input/yelp-dataset/yelp_academic_dataset_business.json", lines="True")
df_5businesses = dataset_business[dataset_business["business_id"].isin(business_mostreviews)]
df_5businessreviews = df_review[df_review["business_id"].isin(business_mostreviews)]
display(df_5businessreviews["stars"].value_counts())
df_5businessreviews.head()

stars
5.0    5526
4.0    3226
3.0    1175
2.0     650
1.0     628
Name: count, dtype: int64

review_id                 user_id             business_id  \
37   pHwbdway4yeI-dSSmZA7-Q  qEEk0PuoH1dVa619t8fgpw  PY9GRfzr4nTZeINf346QOw   
44   jC-fGfx-YLqxVBcyTAd4Pw  EBa-0-6AKoy6jziNexDJtg  W4ZEKkva9HpAdZG88juwyQ   
61   4zopEEPqfwm-c_FNpeHZYw  JYYYKt6TdVA4ng9lLcXt_g  SZU9c8V2GuREDN5KgyHFJw   
108  yyrMqY7sNp5gT7KJ1AaYWA  pitYOVSsF8R1gWG1G0qxsA  GBTPC53ZrG1ZBY3DT8Mbcw   
205  sOIEFZMEzb055tCO_tBSvQ  1xS8Jj23zHx8axIVopG3wA  W4ZEKkva9HpAdZG88juwyQ   

     stars  useful  funny  cool  \
37     4.0       0      0     0   
44     3.0       0      0     0   
61     5.0       0      0     0   
108    4.0       0      0     0   
205    4.0       0      0     0   

                                                  text                 date  
37   We checked in around 2:30 pm.  Check-in was qu...  2017-09-20 16:16:47  
44   In a word... "OVERRATED!".  The food took fore...  2013-12-29 02:37:42  
61   We were a bit weary about trying the Shellfish...  2016-05-31 02:14:54  
108  We have been here twice for brunch and have en...  2016-03-07 17:25:30  
205  Excellent.  Went there for lunch (the budget o...  2011-01-09 03:52:09

In [9]:
# Kelime sayısını hesaplama
df_5businessreviews['word_count'] = df_5businessreviews['text'].apply(lambda x: len(x.split()))

print(df_5businessreviews[['text', 'word_count']].head())

                                                  text  word_count
37   We checked in around 2:30 pm.  Check-in was qu...         237
44   In a word... "OVERRATED!".  The food took fore...          63
61   We were a bit weary about trying the Shellfish...         324
108  We have been here twice for brunch and have en...          40
205  Excellent.  Went there for lunch (the budget o...          59


/tmp/ipykernel_23/759993136.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5businessreviews['word_count'] = df_5businessreviews['text'].apply(lambda x: len(x.split()))


In [10]:
# 80 kelimeden fazla olan yorumları filtreleme, fazlası LLM modelinin kafasını karıştırıyor
df_5businessreviews = df_5businessreviews[df_5businessreviews['word_count'] <= 80]

# Yeni DataFrame, ve satır sayısı kontrolü
df_5businessreviews[['text', 'word_count']]

text  word_count
44      In a word... "OVERRATED!".  The food took fore...          63
108     We have been here twice for brunch and have en...          40
205     Excellent.  Went there for lunch (the budget o...          59
290     OMG! What an amazing dinner experience. A frie...          62
498     Best shrimp and grits in NOLA! Delicious fresh...          29
...                                                   ...         ...
499664  Not worth the 100 bucks we just spent. The foo...          53
499697  This place was great! We popped in right after...          72
499705  Lower garden district location serves consiste...          14
499859  First time visiting Surrey's and I'll have to ...          61
499886  That lobster roll is great, every time we come...          26

[5888 rows x 2 columns]

In [11]:
display(df_5businessreviews["stars"].value_counts()) #Yıldız sayılarında dengesizlik kontrolü

stars
5.0    3341
4.0    1606
3.0     489
1.0     226
2.0     226
Name: count, dtype: int64

In [12]:
# 5 yıldızlı yorumları filtreleme, 1500 rastgele yorumu alma ve sonunda 3341 yorumu 1500'e indirme süreci
#Verileri eşitlemek için ağır basan 5 yıldız sayısını azaltma
if df_5businessreviews[df_5businessreviews['stars'] == 5.0].shape[0] > 1500:
    five_star_sample = df_5businessreviews[df_5businessreviews['stars'] == 5.0].sample(n=1500, random_state=42)
else:
    five_star_sample = df_5businessreviews[df_5businessreviews['stars'] == 5.0]

# 5 yıldız dışındaki yorumları koru
other_reviews = df_5businessreviews[df_5businessreviews['stars'] != 5.0]
df_5businessreviews = pd.concat([five_star_sample, other_reviews], ignore_index=True)
df_5businessreviews = df_5businessreviews.sample(frac=1, random_state=42).reset_index(drop=True)

print("5 yıldızlı yorum sayısı:", df_5businessreviews[df_5businessreviews['stars'] == 5.0].shape[0])
print("Yeni veri çerçevesinin toplam boyutu:", df_5businessreviews.shape)


5 yıldızlı yorum sayısı: 1500
Yeni veri çerçevesinin toplam boyutu: (4047, 10)


In [13]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Stopwords ve lemmatizer yükleme
nltk.download('stopwords')
nltk.download('wordnet')
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package stopwords to /usr/share/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /usr/share/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [14]:
import zipfile
import os

# NLTK'nin veri yolunu bul
nltk_path = nltk.data.find('corpora').path
wordnet_zip_path = os.path.join(nltk_path, 'wordnet.zip')  # wordnet.zip dosyasının yolu
wordnet_extracted_path = os.path.join(nltk_path, 'wordnet')  # Çıkartılacak dizin

# Eğer wordnet klasörü yoksa zip dosyasını çıkar
if not os.path.exists(wordnet_extracted_path):
    with zipfile.ZipFile(wordnet_zip_path, 'r') as zip_ref:
        zip_ref.extractall(nltk_path)
    print("WordNet başarıyla çıkarıldı!")

# Kontrol
print(f"WordNet dosyaları: {os.listdir(wordnet_extracted_path)}")

WordNet başarıyla çıkarıldı!
WordNet dosyaları: ['citation.bib', 'verb.exc', 'index.verb', 'data.adv', 'README', 'noun.exc', 'LICENSE', 'index.adj', 'index.sense', 'adv.exc', 'data.verb', 'index.noun', 'data.adj', 'index.adv', 'adj.exc', 'lexnames', 'cntlist.rev', 'data.noun']


In [15]:
def cleaning_text(text):
  # Noktalama işaretlerini ve sayıları kaldırma fonksiyonu
  text = re.sub(r"[^\w\s]", "", text)  # Noktalama
  text = re.sub(r"\d+", "", text)      # Sayılar
  text = re.sub(r"\s+", " ", text.strip()) # Fazladan boşluklar
  text = text.lower()
  # Stopwords kaldır ve lemmatize et
  text = " ".join([lemmatizer.lemmatize(word) for word in text.split() if word not in stop_words])
  return text

In [16]:
# Reviews tablosundaki yorumları temizleme
df_5businessreviews.loc[:, 'cleaned_text'] = df_5businessreviews['text'].apply(cleaning_text)
# Temizlenmiş veriyi kontrol
df_5businessreviews[['text', 'cleaned_text']].head()

text  \
0  Imperial Suite for our anniversary, we loved i...   
1  Excellent in one word!!!  Since I am not allow...   
2  Food was good, way over priced for the quality...   
3  We ate here because we needed parking validati...   
4  I don't know how the reviews for this place ar...   

                                        cleaned_text  
0  imperial suite anniversary loved remodeled hot...  
1  excellent one word since allowed one word revi...  
2  food good way priced quality started wedge sal...  
3  ate needed parking validation food alright thi...  
4  dont know review place high worst crab sandwic...

In [17]:
!pip install sentence-transformers

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 7.3 MB/s eta 0:00:00:00:01


In [18]:
from sentence_transformers import SentenceTransformer
import numpy as np

# SBERT model yükleme sürecim
model = SentenceTransformer('paraphrase-MiniLM-L3-v2')

# Embedding'leri oluşturduğum alan
texts = df_5businessreviews['cleaned_text'].tolist()  # Yorum metinlerini al
embeddings = model.encode(texts, batch_size=128, show_progress_bar=True)  # Embedding'leri çıkar

# Embedding'leri saklama
np.save('business_reviews_embeddings.npy', embeddings)

# oluşturulan embedding boyutu
print("Embedding'lerin boyutu:", embeddings.shape)

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/4.04k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/69.6M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/314 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/32 [00:00<?, ?it/s]

Embedding'lerin boyutu: (4047, 384)


In [19]:
# Embedding'leri ve hedef değişkeni tanımla
X = embeddings  # SBERT embedding'leri
y = df_5businessreviews['stars']  # yıldız kolonu sınıflar

In [20]:
#1,2,3 yıldızlı yorum sayısı az olduğu için sınıflandırma dengesizliğini azaltmak için yorum sayılarını arttırma işlemi
from imblearn.over_sampling import SMOTE
import numpy as np
import pandas as pd

# SMOTE işlemi için X (embedding'ler) ve y (hedef değişken)
smote = SMOTE(random_state=42, sampling_strategy={1.0: 1000, 2.0: 1000, 3.0: 1000})

# Azınlık sınıflarını artırma sürecim
X_smote, y_smote = smote.fit_resample(X, y)

# Sınıf dağılımını print ettiğim kısım
print("SMOTE sonrası sınıf dağılımı:")
print(pd.Series(y_smote).value_counts())

SMOTE sonrası sınıf dağılımı:
stars
4.0    1606
5.0    1500
3.0    1000
2.0    1000
1.0    1000
Name: count, dtype: int64


In [21]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

# SMOTE sonrası veriyi bölme
X_train, X_test, y_train, y_test = train_test_split(X_smote, y_smote, test_size=0.3, random_state=42, stratify=y_smote)

# Random Forest Modeli
rf_model = RandomForestClassifier(class_weight='balanced', random_state=42)
rf_model.fit(X_train, y_train)  # Modeli eğitme

# Test seti üzerinde tahmin
y_pred = rf_model.predict(X_test)

# Performans değerlendirme
print("Sınıflandırma Raporu:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Sınıflandırma Raporu:
              precision    recall  f1-score   support

         1.0       0.87      0.98      0.92       300
         2.0       0.92      0.89      0.90       300
         3.0       0.91      0.63      0.74       300
         4.0       0.50      0.60      0.54       482
         5.0       0.53      0.50      0.51       450

    accuracy                           0.69      1832
   macro avg       0.75      0.72      0.72      1832
weighted avg       0.70      0.69      0.69      1832

Confusion Matrix:
[[293   0   0   4   3]
 [  7 266   4  13  10]
 [ 18  10 189  60  23]
 [ 11  11  11 288 161]
 [  6   3   4 214 223]]


In [22]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

# SMOTE sonrası veriyi bölme
X_train, X_test, y_train, y_test = train_test_split(X_smote, y_smote, test_size=0.3, random_state=42, stratify=y_smote)

# Logistic Regression Modeli
logreg = LogisticRegression(class_weight='balanced', max_iter=2000, random_state=42)
logreg.fit(X_train, y_train)  # Modeli eğitme

# Test seti üzerinde tahmin
y_pred = logreg.predict(X_test)

# Performans değerlendirme
print("Sınıflandırma Raporu:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Sınıflandırma Raporu:
              precision    recall  f1-score   support

         1.0       0.78      0.89      0.83       300
         2.0       0.70      0.77      0.73       300
         3.0       0.59      0.63      0.61       300
         4.0       0.52      0.45      0.48       482
         5.0       0.59      0.56      0.58       450

    accuracy                           0.63      1832
   macro avg       0.64      0.66      0.65      1832
weighted avg       0.62      0.63      0.63      1832

Confusion Matrix:
[[268  12   7   3  10]
 [ 22 231  33  11   3]
 [ 16  29 190  51  14]
 [ 18  39  64 215 146]
 [ 18  19  28 132 253]]


In [23]:
# Gerekli verileri alarak yeni dataframe oluşturma süreci
df = df_5businessreviews[['stars', 'text']].copy()
print(df.head())

# Yorum sayısı kontrolü
print(f"Toplam yorum sayısı: {len(df)}")

# LLM'e öğretilecek verileri kaydetme
df.to_csv("llm_training_data.csv", index=False)  # Eğitilecek veri seti
print("Veri eğitime hazır.")


   stars                                               text
0    4.0  Imperial Suite for our anniversary, we loved i...
1    5.0  Excellent in one word!!!  Since I am not allow...
2    3.0  Food was good, way over priced for the quality...
3    2.0  We ate here because we needed parking validati...
4    1.0  I don't know how the reviews for this place ar...
Toplam yorum sayısı: 4047
Veri eğitime hazır.


In [24]:
# Satırların LLM'e sokmadan önce bir sıkıntı çıkmaması adına genel kontrolü
df['text_length'] = df['text'].apply(lambda x: len(x.split()))

print("Minimum uzunluk:", df['text_length'].min())
print("Maksimum uzunluk:", df['text_length'].max())
print("Ortalama uzunluk:", df['text_length'].mean())
print("Medyan uzunluk:", df['text_length'].median())

print("\nUzunluk dağılımı:")
print(df['text_length'].describe())


Minimum uzunluk: 1
Maksimum uzunluk: 80
Ortalama uzunluk: 44.484556461576474
Medyan uzunluk: 43.0

Uzunluk dağılımı:
count    4047.000000
mean       44.484556
std        18.684246
min         1.000000
25%        29.000000
50%        43.000000
75%        60.000000
max        80.000000
Name: text_length, dtype: float64


In [25]:
from transformers import AutoTokenizer, AutoModelForCausalLM, Trainer, TrainingArguments, DataCollatorForLanguageModeling
from datasets import Dataset
from sklearn.model_selection import train_test_split
import os

# Eğitim sırasında metrikleri kayıt etmeyi devre dışı bıraktım
os.environ["WANDB_DISABLED"] = "true"

# Veri setini yükleme kısmı
train_df, eval_df = train_test_split(df, test_size=0.2, random_state=42)

# Dataset objelerine dönüştürme
train_dataset = Dataset.from_pandas(train_df)
eval_dataset = Dataset.from_pandas(eval_df)

# Model ve tokenizer yüklediğim yer (DistilGPT-2)
model_name = "distilgpt2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

# Padding süreci
tokenizer.pad_token = tokenizer.eos_token

# Yıldız ve metni birleştirip input metni oluşturma ve modelin anlayacağı formata evriltme
def preprocess_data(example):
    example['input_text'] = f"Star Rating: {example['stars']}\nReview: {example['text']}"
    return example

# Dataset'i işleme kısmı
train_dataset = train_dataset.map(preprocess_data)
eval_dataset = eval_dataset.map(preprocess_data)

# aynı uzunlukta tutma ve tokenlara bölme
def tokenize_function(examples):
    return tokenizer(examples['input_text'], padding="max_length", truncation=True)

# veri setini tokenize etme
train_dataset = train_dataset.map(tokenize_function, batched=True)
eval_dataset = eval_dataset.map(tokenize_function, batched=True)

# model girişi düzenleme
data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False, 
)

# Model eğitim ayarları
training_args = TrainingArguments(
    output_dir="./results",
    evaluation_strategy="epoch", 
    learning_rate=5e-5,
    per_device_train_batch_size=8,
    num_train_epochs=3,
    weight_decay=0.01,
    save_steps=500,
    save_total_limit=2,
    logging_dir='./logs',
    report_to="none",
)

# Trainer tanımlama
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    tokenizer=tokenizer,
    data_collator=data_collator,
)

trainer.train()

# Eğitilen modeli kaydetme
model.save_pretrained("/kaggle/working/distilgpt2_model")
tokenizer.save_pretrained("/kaggle/working/distilgpt2_model")
print("DistilGPT-2 modeli başarıyla eğitildi ve kaydedildi.")


tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/762 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/353M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

Map:   0%|          | 0/3237 [00:00<?, ? examples/s]

Map:   0%|          | 0/810 [00:00<?, ? examples/s]

Map:   0%|          | 0/3237 [00:00<?, ? examples/s]

Map:   0%|          | 0/810 [00:00<?, ? examples/s]

/opt/conda/lib/python3.10/site-packages/transformers/training_args.py:1568: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_23/3484567264.py:62: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py:79: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.device(device), torch.cuda.stream(stream), autocast(enabled=autocast_enabled):
/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py:79: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.device(device), torch.cuda.stream(stream), autocast(enabled=autocast_enabled):
/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py:79: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.device(device), torch.cuda.stream(stream), autocast(enabled=autocast_enabled):
/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0

DistilGPT-2 modeli başarıyla eğitildi ve kaydedildi.


In [28]:
from transformers import AutoTokenizer, AutoModelForCausalLM
import re

# Eğittiğiniz modeli yükleyin
model_path = "/kaggle/working/distilgpt2_model"  # Eğitilen modelin kaydedildiği klasör
tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModelForCausalLM.from_pretrained(model_path)

# Yıldız derecesini prompt'tan çıkarma
def extract_star_rating(user_input):
    match = re.search(r'\b[1-5]\b', user_input)
    return int(match.group()) if match else None

# Yorum üretme
def generate_review(user_input, max_length=50):
    star_rating = extract_star_rating(user_input)
    if not star_rating:
        return "Geçerli bir yıldız derecesi girin (1-5)."
    prompt = f"Star Rating: {star_rating}\nReview:"
    inputs = tokenizer(prompt, return_tensors="pt")
    outputs = model.generate(inputs.input_ids, max_length=max_length, do_sample=True, temperature=0.7)
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

# Örnek Kullanım
print(generate_review("5 yıldızlı bir yorum yap"))
print(generate_review("3 yıldızlı yorum hazırla"))


The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.


Star Rating: 5
Review: Very nice place for a great lunch spot.  Service was great and the service was good.  We have been here a few times in the past several years.  The Oysters were very good.  My
Star Rating: 3
Review: My husband and I ate here the previous day, and we had the shrimp and grits.     

We enjoyed the shrimp and grits, which was great.  

Our


In [29]:
import shutil

# zip formatında kaydetme
shutil.make_archive('/kaggle/working/distilgpt2_model', 'zip', '/kaggle/working/distilgpt2_model')

print("Model sıkıştırıldı: distilgpt2_model.zip")


Model sıkıştırıldı: distilgpt2_model.zip
